default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PG_HOST'] || '127.0.0.1' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  username: <%= ENV['PG_USER'] || 'root' %>
  password: <%= ENV['PG_PASS'] %>

development:
  <<: *default
  database: ghost_notes_api_development

test:
  <<: *default
  database: ghost_notes_api_test

production:
  <<: *default
  database: ghost_notes_api_production
